### PR TITLE
Improves the how many days of PTO section.

### PR DESCRIPTION
**Pull request by wintermeyer**
I have the feeling that our 22 days of PTO wording is not clear enough for people from all countries and for someone who reads through it in a hurry. It is important that everybody understands right away the the sum of our calculation adds up to 35 days of PTO. Therefor we should start with that number.

### CODE REVIEW

**Review by kennyadsl — COMMENTED** [review]
I think this is way more clear, but I'll leave the approval to someone more experienced with this topic. Added @mtylty and @matteogalliani as reviewers. Thanks @wintermeyer!!!

**Review by matteogalliani — APPROVED** [review]
I like it! Your description sounds neater and clearer. Thanks for this change @wintermeyer

**Review by aldesantis — APPROVED** [review]
Looks good! Just one nit: I would use "tenure" instead of "length of service." I recently found that that's the right word for "how long someone has been at your company." 😄

**Comment by matteogalliani** [comment]
It is definitely `Tenure` :D

**Review by aldesantis — APPROVED** [review]

**Comment by kennyadsl** [comment]
I did ask @wintermeyer to rebase the PR in Slack 😬. My fault for not asking here and block the PR instead. @wintermeyer just keep that in mind for the next time.

**Pull request merged**
