### PR TITLE
Rails migrations info on `ActiveRecord::ConcurrentMigrationError`

### PR DESCRIPTION
**Pull request by spaghetticode**
We must avoid the error `ActiveRecord::ConcurrentMigrationError` when deploying
our applications as this may lead to code inconsistencies and errors.

### CODE REVIEW

**Comment by aldesantis** [comment]
@spaghetticode we'll keep this open because we're translating the playbook into English. Once done, we'll translate this PR and merge.

**Comment by kennyadsl** [comment]
What about writing a small blog post instead and link it here?

**Comment by spaghetticode** [comment]
sounds good to me!

**Comment by aldesantis** [comment]
@spaghetticode I agree, will close this for now.

**Pull request closed without merging**
