### PR TITLE
Add hire kit picture

### PR DESCRIPTION
**Pull request by mtylty**
Not much else, what the title says.

### CODE REVIEW

**Comment by kennyadsl** [comment]
@mtylty 10MB seems like a lot for a website, are we optimizing images when building the static website?

**Review by matteogalliani — APPROVED** [review]
cool!

**Comment by mtylty** [comment]
@kennyadsl good catch, regardless of production optimizations there is no need to have a 10mb img in the repo.

**Review by mfrecchiami — APPROVED** [review]
Hi @mtylty, thanks!
I've reduced the file weight and update the image size (same body width) 🖼️

**Pull request merged**
